name: Test PostgreSQL UDF

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: example

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: docker build -t postgres-udf-test .

      - name: Run PostgreSQL UDF Test
        run: |
          # Ensure any previous container is removed
          docker rm -f postgres-test || true

          # Run the new container with the password
          docker run -d --name postgres-test -p 5432:5432 -e POSTGRES_PASSWORD=example postgres-udf-test

          # Wait for PostgreSQL to initialize
          sleep 60

          # Check container logs for troubleshooting
          docker logs postgres-test

          # Check PostgreSQL is ready
          until docker exec -u postgres postgres-test pg_isready; do
            sleep 5
          done

          # Run the extension creation and test commands
          docker exec -u postgres postgres-test psql -U postgres -c "CREATE EXTENSION string_udf;"
          docker exec -u postgres postgres-test psql -U postgres -c "SELECT string_udf('Hello, World!');"
